steps:
    -
        name: gcr.io/cloud-builders/docker
        args:
            - build
            - '-t'
            - 'gcr.io/tugas-386410/crud-op:cloudbuild-$BRANCH_NAME-$SHORT_SHA'
            - .
    -
    
   
        name: gcr.io/cloud-builders/docker
        args:
            - tag
            - 'gcr.io/tugas-386410/crud-op:cloudbuild-$BRANCH_NAME-$SHORT_SHA'
            - 'gcr.io/tugas-386410/crud-op:cloudbuild-$BRANCH_NAME-latest'
            
    -
        name: 'gcr.io/cloud-builders/docker'
        args:
            - push 
            - 'gcr.io/tugas-386410/crud-op:cloudbuild-$BRANCH_NAME-$SHORT_SHA'
    -
            
        name: 'gcr.io/cloud-builders/docker'
        args:
            - push 
            - 'gcr.io/tugas-386410/crud-op:cloudbuild-$BRANCH_NAME-latest'
            
   
    -
        name: gcr.io/cloud-builders/gcloud
        args:
            - beta
            - run
            - deploy
            - crud-op-$BRANCH_NAME
            - '--image'
            - 'gcr.io/tugas-386410/crud-op:cloudbuild-$BRANCH_NAME-latest'
            - '--region'
            - us-central1
            - '--platform'
            - managed
            - '--allow-unauthenticated'
images:
          - 'gcr.io/tugas-386410/crud-op:cloudbuild-$BRANCH_NAME-$SHORT_SHA'
          - 'gcr.io/tugas-386410/crud-op:cloudbuild-$BRANCH_NAME-latest'
